### PR TITLE
adds error message for clash between file names and function names

### PR DESCRIPTION
**Pull request by gulliverhan**
addresses #18 #51  where code fails silently when a script file name is the same as a function name
- On pull & push, parses the new code set to identify all function names
- checks the script file names against all function names
- if there is a match, shows an error and where the change should be made
- uses acorn_loose.parse_dammit as a parser as this is much more tolerant of invalid javascript such as a completely empty script file.

Please let me know if you have any comments or suggestions :-)

### CODE REVIEW

**Comment by leonhartX** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR, try to keep changes smaller if you can</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by leonhartX** [comment]
Thanks for this.
But the actually issue is we can not get correct file content when function name conflicted because the RPC response format is broken.
like this: 



So is simply just when get to the analysis step.

**Comment by andrewmoise** [comment]
Would it be possible to merge this? This was causing me unending issues until I dug through the issue reports and learned I had to rename my files for things to work. :-) I think having a function named the same thing as the file that contains it is a pretty common thing (it is for me).

I can do the work to produce an up-to-date merge request if that's useful.

Thanks again for making this, the plugin is awesome!

**Comment by leonhartX** [comment]
@andrewmoise as I mentioned in the comment, this is not a really fix and it won't help anything

**Comment by andrewmoise** [comment]
Ah gotcha, I didn't read closely enough. Definitely this issue is causing brokenness for me... now that I understand the issue I just renamed all my files into a format that will never duplicate the class names. Before I understood what was going on though I had a ton of commits talking about the broken plugin / trying to deal with it blanking out file contents and committing stuff separately.

Is there any other approach that can avoid this? Clearly whatever the actual GAS editor is doing to communicate back and forth with the server isn't subject to the brokenness... is it possible to just use the same interface that they're using? Or detect when it's showing a file as empty and issue a warning (since GAS doesn't allow empty files in a project)?

**Pull request closed without merging**
