### PR TITLE
gets baseUrl from gasUrl

### LINKED ISSUE #65: Push/Pull deleting files
I tried pushing my latest commit and it ended up removing all of my files from GitHub as if they were not there. Then, when I tried to pull from another branch, it tried to duplicate all files. Please fix.

### PR DESCRIPTION
**Pull request by gulliverhan**
should fix #65 #66 #67 
looks like there are some situations where the header I was using previously isn't getting set which could be causing these issues.  This commit uses the gasUrl value which should always be available to this function to work out the correct baseUrl taking into account both bound / non bound behaviour & regular Google accounts / corporate Google Apps domains

### CODE REVIEW

**Comment by leonhartX** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">manifest is not changed, forget to bump version?</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by leonhartX** [comment]
Thanks, I'll check this ASAP.
But please update the version to the correct one:3.3.4

**Comment by gulliverhan** [comment]
done :-)

**Comment by leonhartX** [comment]
LGTM, thanks!

**Pull request merged**
