### PR TITLE
Fix/update to circleci 2.0

### PR DESCRIPTION
**Pull request by plumSemPy**
@leonhartX:
Update circle to run on circle 2.0. 

Circle 1 will be deprecated end of August 2018.
I apologize as I did not have a `danger` account, so my tests are breaking on `run: danger`. 

I removed some of the excludes from the gzip because the `deploy-to-production` checks out the repo again and it does not have most of the excluded folders and files.

Please let me know if you want anything changed.

### CODE REVIEW

**Comment by leonhartX** [comment]
thanks for this, (sorry I replied soooo late)
but i'm considering move ci to other services than circleci.
and currently the v1 still can work so it's not emergency

**Comment by plumSemPy** [comment]
If you are moving the builds that is fine. But Circle 1.0 does not build anymore, see [here](https://circleci.com/blog/sunsetting-1-0/)

**Comment by leonhartX** [comment]
yes, i know, but actually it still can build v1 now.
https://circleci.com/gh/leonhartX/gas-githupb/145

**Comment by plumSemPy** [comment]
haha lucky you then, don't tell them.

**Comment by leonhartX** [comment]
actually don't have time to do the CI migration in the past two years 😂 
will just merge this, thanks for the contribution!

**Pull request merged**
